# Generated by Django 5.2.12 on 2026-03-13 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('domain', models.CharField(max_length=255)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('overall_score', models.IntegerField(default=0)),
                ('ssl_score', models.IntegerField(default=0)),
                ('headers_score', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=0)),
                ('techstack_score', models.IntegerField(default=0)),
                ('dns_score', models.IntegerField(default=0)),
                ('mobile_score', models.IntegerField(default=0)),
                ('ssl_data', models.JSONField(default=dict)),
                ('headers_data', models.JSONField(default=dict)),
                ('performance_data', models.JSONField(default=dict)),
                ('techstack_data', models.JSONField(default=dict)),
                ('dns_data', models.JSONField(default=dict)),
                ('mobile_data', models.JSONField(default=dict)),
                ('paid', models.BooleanField(default=False)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
